-- 코드를 작성해주세요
SELECT CHILD.ID
FROM ECOLI_DATA CHILD
JOIN ECOLI_DATA PARENT
    ON CHILD.PARENT_ID = PARENT.ID
JOIN ECOLI_DATA ROOT
    ON PARENT.PARENT_ID = ROOT.ID
WHERE ROOT.PARENT_ID IS NULL
ORDER BY CHILD.ID ASC;