-- 코드를 입력하세요
SELECT CRCC.CAR_ID
    , CRCC.CAR_TYPE
    , ROUND((CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) * 0.01 * 30), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
    ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
    AND CRCDP.DURATION_TYPE LIKE '30%'
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE <= '2022-11-30')
        AND (END_DATE >= '2022-11-01')
)
    AND CRCC.CAR_TYPE IN ('세단', 'SUV')
    AND (CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) * 0.01 * 30) >= 500000
    AND (CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) * 0.01 * 30) < 2000000
ORDER BY FEE DESC, CRCC.CAR_TYPE, CRCC.CAR_ID DESC;