-- 코드를 작성해주세요
SELECT 
    A.ID AS ID,
    CASE WHEN A.COLONY = 1 THEN 'CRITICAL'
        WHEN A.COLONY = 2 THEN 'HIGH'
        WHEN A.COLONY = 3 THEN 'MEDIUM'
        WHEN A.COLONY = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT 
        ID, 
        NTILE(4) OVER (
            ORDER BY SIZE_OF_COLONY DESC
        ) AS COLONY
    FROM ECOLI_DATA
) AS A
ORDER BY ID;