-- 코드를 입력하세요
SELECT MP.MEMBER_NAME AS MEMEBER_NAME
    , RR.REVIEW_TEXT AS REVIEW_TEXT
    , RR.REVIEW_DATE AS REIVEW_DATE
FROM MEMBER_PROFILE MP
INNER JOIN REST_REVIEW RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;