-- 코드를 작성해주세요
-- ID, GENOTYPE, PARENT_GENOTYPE 출력
SELECT A.ID AS ID, A.GENOTYPE AS GENOTYPE, (
    SELECT GENOTYPE
    FROM ECOLI_DATA
    WHERE A.PARENT_ID = ID
) AS PARENT_GENOTYPE
FROM ECOLI_DATA A
WHERE (A.GENOTYPE & (
    SELECT B.GENOTYPE
    FROM ECOLI_DATA B
    WHERE A.PARENT_ID = B.ID
)) = (SELECT GENOTYPE
    FROM ECOLI_DATA
    WHERE A.PARENT_ID = ID)
ORDER BY ID;